[build]
builder = "nixpacks"
buildCommand = "node scripts/check-npm-version.js && npm ci --only=production"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production" 