[build]
builder = "nixpacks"
buildCommand = "node scripts/check-npm-version.js && npm ci --only=production"

[deploy]
startCommand = "node server-minimal.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
terminationGracePeriodSeconds = 60

[env]
NODE_ENV = "production"
DEBUG = "true"
SHUTDOWN_TIMEOUT = "45000"
# Use minimal server for now to debug health check issues
USE_MINIMAL_SERVER = "true" 