[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production" 