[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "node server-postgres-minimal.js"
restartPolicyType = "always"
terminationGracePeriodSeconds = 30

[env]
NODE_ENV = "production"
DEBUG = "false"
SHUTDOWN_TIMEOUT = "45000"

# PostgreSQL configuration (add PostgreSQL plugin in Railway dashboard)
# DATABASE_URL will be automatically provided by Railway PostgreSQL plugin 