[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/startup.sh"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 60

[env]
NODE_ENV = "production" 