[build]
builder = "nixpacks"
buildCommand = "node scripts/check-npm-version.js && npm ci --only=production"

[deploy]
startCommand = "npm run railway-deploy && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
terminationGracePeriodSeconds = 60

[env]
NODE_ENV = "production"
DEBUG = "false"
SHUTDOWN_TIMEOUT = "45000" 