[build]
builder = "nixpacks"
buildCommand = "node scripts/check-npm-version.js && npm ci --only=production"

[deploy]
startCommand = "node server-fixed.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 1
terminationGracePeriodSeconds = 30

[env]
NODE_ENV = "production"
DEBUG = "true"
SHUTDOWN_TIMEOUT = "45000"
# Use minimal server for now to debug health check issues
USE_MINIMAL_SERVER = "true" 